database_name: bdl_dobrostan.db
params:
  level:
  - 0 # 5 - powiaty 2 - wojewodztwa 0 - Polska
  - 2
  unit-level: 
  - 0
  - 2
  format: json
  page-size: 17
years_from: 2020
variables:
  - id: 7737 # Przeciętne miesięczne wydatki w tysiącach złotych na jedną osobę
    name: miesięczne wydatki
  - id: 1725015 # Wskaźnik urbanizacji w procentach
    name: urbanizacja
  - id: 155037 # Poszkodowani w wypadkach przy pracy na 10 tysięcy pracujących
    name: poszkodowani w wypadkach przy pracy
  - id: 1609531 # Liczba zatrudnionych na stanowiskach pracy, w których wyeliminowano lub ograniczono ryzyko zawodowe na stu zatrudnionych w zakładach objętych badaniem
    name: zatrudnieni z ograniczonymi ryzykami
  - id: 454185 # Liczba lekarzy przypadająca na 10 tysięcy ludności
    name: lekarze
  - id: 1365344 # Liczba prób samobójczych 100 tysięcy ludności
    name: próby samobójcze
  - id: 1632971 # Wskaźnik osób dorosłych uczestniczących w kształceniu lub szkoleniu w wieku 25-64 lata w procentach
    name: kształcenei dorosłych
  - id: 60189 # Księgozbiór bibliotek na 10 ludności
    name: księgozbiór
  - id: 288082 # Długość drogi dla rowerów na 100 tysięcy ludności
    name: droga rowerowa
  - id: 1724791 # Powierzchnia parków, zieleńców i terenów zieleni osiedlowej na 1 mieszkańca w metrach kwadratowych
    name: parki
  - id: 1606668 # Subiektywna pozytywna (dobra) ocena sytuacji materialnej gospodarstw domowych w procentach
    name: subiektywna dobra ocena
  - id: 454050 # Subiektywna pozytywna (raczej dobra) ocena sytuacji materialnej gospodarstw domowych w procentach
    name: subiektywna raczej dobra ocena
retries:
  max_retries: 3
  backoff_factor: 1
  status_forcelist:
  - 500
  - 502
  - 503
  - 504
units:
  - id: 000000000000
    name: POLSKA
  - id: 011200000000
    name: MAŁOPOLSKIE
  - id: 012400000000
    name: ŚLĄSKIE
  - id: 020800000000
    name: LUBUSKIE
  - id: 023000000000
    name: WIELKOPOLSKIE
  - id: 023200000000
    name: ZACHODNIOPOMORSKIE
  - id: 030200000000
    name: DOLNOŚLĄSKIE
  - id: 031600000000
    name: OPOLSKIE
  - id: 040400000000
    name: KUJAWSKO-POMORSKIE
  - id: 042200000000
    name: POMORSKIE
  - id: 042800000000
    name: WARMIŃSKO-MAZURSKIE
  - id: 051000000000
    name: ŁÓDZKIE
  - id: 052600000000
    name: ŚWIĘTOKRZYSKIE
  - id: 060600000000
    name: LUBELSKIE
  - id: 061800000000
    name: PODKARPACKIE
  - id: 062000000000
    name: PODLASKIE
  - id: 071400000000
    name: MAZOWIECKIE